# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('table_width', models.IntegerField(default=0)),
                ('table_height', models.IntegerField(default=0)),
                ('bombs_discovered', models.IntegerField(default=0)),
                ('bombs_left', models.IntegerField(default=0)),
            ],
        ),
    ]
