# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='bombs_discovered',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='bombs_left',
        ),
    ]
